//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wyszukiwarka_publikacji_v0._2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArticleProjDBEntities : DbContext
    {
        public ArticleProjDBEntities()
            : base("name=ArticleProjDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorSet> AuthorSet { get; set; }
        public virtual DbSet<PG_ArticlesSet> PG_ArticlesSet { get; set; }
        public virtual DbSet<PP_ArticlesSet> PP_ArticlesSet { get; set; }
        public virtual DbSet<Terms_Vocabulary> Terms_Vocabulary { get; set; }
        public virtual DbSet<UG_ArticlesSet> UG_ArticlesSet { get; set; }
        public virtual DbSet<UMK_ArticlesSet> UMK_ArticlesSet { get; set; }
        public virtual DbSet<WSB_ArticlesSet> WSB_ArticlesSet { get; set; }
    }
}
