//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wyszukiwarka_publikacji_v0._2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArticleDBDataModelContainer : DbContext
    {
        public ArticleDBDataModelContainer()
            : base("name=ArticleDBDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> AuthorSet { get; set; }
        public virtual DbSet<PG_Articles> PG_ArticlesSet { get; set; }
        public virtual DbSet<PP_Articles> PP_ArticlesSet { get; set; }
        public virtual DbSet<UG_Articles> UG_ArticlesSet { get; set; }
        public virtual DbSet<UMK_Articles> UMK_ArticlesSet { get; set; }
        public virtual DbSet<WSB_Articles> WSB_ArticlesSet { get; set; }
        public virtual DbSet<Terms_Vocabulary> Terms_Vocabulary { get; set; }
    }
}
