//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wyszukiwarka_publikacji_v0._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuthorSet()
        {
            this.PG_ArticlesSet = new HashSet<PG_ArticlesSet>();
            this.PP_ArticlesSet = new HashSet<PP_ArticlesSet>();
            this.UG_ArticlesSet = new HashSet<UG_ArticlesSet>();
            this.UMK_ArticlesSet = new HashSet<UMK_ArticlesSet>();
            this.WSB_ArticlesSet = new HashSet<WSB_ArticlesSet>();
        }
    
        public int author_Id { get; set; }
        public string author_name { get; set; }
        public string author_surename { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PG_ArticlesSet> PG_ArticlesSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PP_ArticlesSet> PP_ArticlesSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UG_ArticlesSet> UG_ArticlesSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMK_ArticlesSet> UMK_ArticlesSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WSB_ArticlesSet> WSB_ArticlesSet { get; set; }
    }
}
